name: Mobcraft
version: 1.0-SNAPSHOT
main: org.bench245.mobcraft.Mobcraft
api-version: 1.21

commands:
  setmob:
    description: Sets a player's mob
    usage: /setmob <player> <mob>

  loottoggle:
    description: Toggles loot drops for specified mobs
    usage: /loottoggle <enable|disable|add|remove> [mobType]
    aliases: [lt]

  flight:
    description: Toggles flight for the current player and lets operators manage who can fly
    usage: /flight <add|remove> [player] [speed]
    aliases: [fly]

  giveitem:
    description: Gives a mob-specific item or arrow
    usage: /giveitem <mobType|arrow> [effect] [amount]
    aliases: [gi]
  revive:
    description: Revive a punished player
    usage: /revive <player>
    permission: mobcraft.revive

  enchest:
    description: Opens your ender chest if you are a Tuff Golem
    usage: /enchest
    aliases: [echest]

  mount:
    description: Mounts a player if you are a Ghast
    usage: /mount
