name: Mobcraft
version: '1.0-SNAPSHOT'
main: org.bench245.mobcraft.Mobcraft
api-version: '1.21'
commands:
  setmob:
    description: Sets a players mob
    usage: /setmob <player> <mob>
  loottoggle:
    description: Toggles loot drops for specified mobs.
    usage: /loottoggle <enable|disable|add|remove> [mobType]
    aliases: [lt]
  flight:
    description: Toggles flight the current player and lets operators manage who can fly.
    usage: /flight <add|remove> [player] [speed]
    aliases: [fly]
depend: [ProtocolLib]